use data_analyst_project

select * from customer_behaviour_analysis

--1. which category generates highest revenue ?

select 
	category,
	round(sum(purchase_amount),2) as highest_revenue
from customer_behaviour_analysis
group by category
order by highest_revenue desc

--2. Are discounts actually increasing purchase value ?

select
	discount_applied,
	round(sum(purchase_amount),2) as total_revenue
	from customer_behaviour_analysis
	group by discount_applied

--3.What is the total revenue generated by male and female customer

select 
	gender,
	round(sum(purchase_amount),2) as highest_revenue,
	round(avg(purchase_amount),2) as avg_revenue
from customer_behaviour_analysis
group by gender	
order by highest_revenue desc

--4.Which customer used a discount but still spent more then the average purchase amount ?
select * from customer_behaviour_analysis

select top 10
	customer_id,
	purchase_amount,
	discount_applied
from customer_behaviour_analysis
where discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount) from customer_behaviour_analysis)

--5.WHich are the top/bottom products with highest average review rating.
select * from customer_behaviour_analysis

select top 5
	item_purchased,
	round(avg(review_rating),2) as avg_ratings
from customer_behaviour_analysis
group by item_purchased
order by avg_ratings desc

select top 5
	item_purchased,
	round(avg(review_rating),2) as avg_ratings
from customer_behaviour_analysis
group by item_purchased
order by avg_ratings asc

--6. Average purchase : standard vs express shipping
select * from customer_behaviour_analysis

select
	shipping_type,
	count(distinct customer_id) as order_placesd,
	round(avg(purchase_amount),2) as avg_purchase,
	round(sum(purchase_amount),2) as revenue
	from customer_behaviour_analysis
--where shipping_type in ('standard','express')
group by shipping_type
order by revenue desc

--7. Do subscibed customers spend more ? compare average spend and total revenue between subscribers and non-subscribers.
select * from customer_behaviour_analysis

select 
	subscription_status,
	count(customer_id) as users,
	round(avg(purchase_amount),2) as avg_revenue,
	round(sum(purchase_amount),2) as total_revenue
from customer_behaviour_analysis
group by subscription_status

--8. Top 5 products with highest discount usage %

select top 5 
	item_purchased,
	count(item_purchased) as total_number_of_times_sold,
	count(case when discount_applied='Yes' then 1 end) as number_of_times_sold_when_discount_applied,
	count(case when discount_applied='Yes' then 1 end) *100.0 / count(*) as discount_percent
from customer_behaviour_analysis
group by item_purchased
order by discount_percent desc

--9. Segment customer into new,returning and loyal based on their total number number of previous purchase,
--and show the count of each segment

select
	case 
		when previous_purchases= '0' then 'new customer'
		when previous_purchases between 1 and 15 then 'returning customer'
	else 'loyal customer'
end as customer_segment,
count(*) as cutomer_count
from customer_behaviour_analysis
group by case 
		when previous_purchases= '0' then 'new customer'
		when previous_purchases between 1 and 15 then 'returning customer'
	else 'loyal customer'
end 

--10 . What are top 3 most purchased products within each category ?

select * from  customer_behaviour_analysis

with cte as
(
select 
	category,
	item_purchased,
	count(item_purchased) as most_purchased,
	rank()over(partition by category order by (item_purchased) desc) as rnk
from customer_behaviour_analysis
group by category,item_purchased
)
select * from cte
where rnk<=3

--11. Are the customer who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?

select
	case
		when previous_purchases > 5 then 'repeated buyers'
		else 'normal buyers'
	end as customer_type,
	subscription_status,
	count(*) as customer_count,
	count(*) *100.0/ sum(count(*)) over (partition by case
										when previous_purchases > 5 then 'repeated buyers'
										else 'normal buyers'
										end
										) as percents
from customer_behaviour_analysis
group by
	case
		when previous_purchases > 5 then 'repeated buyers'
		else 'normal buyers'
	end, subscription_status

--12 . What is the revenue contribution of each age group ?

select 
	case
		when age between 18 and 25 then '18-25'
		when age between 26 and 35 then '26-35'
		when age between 36 and 50 then '35-50'
	else '51+'
end as age_group,
round(sum(purchase_amount),2) as total_revenue
from customer_behaviour_analysis
group by 	case
		when age between 18 and 25 then '18-25'
		when age between 26 and 35 then '26-35'
		when age between 36 and 50 then '35-50'
	else '51+'
end
order by total_revenue desc









